### ISSUE TITLE
To do regarding first release

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Wiccan_Arts#26]
In no particular order

- [x] Fix taglock
- [x] Fix candles
- [x] Fix apiary issues
- [x] Fix kettle issues
- [x] Finish implementation of kettle, including recipes
- [ ] Rework easter egg recipe (kettle crafting advancement logic is needed)
- [x] Fix tabs
- [ ] More brews, obviously.
- [x] Fix oil and honey textures, for they mismatch
- [x] Add BiomeDictionary-centric oregen
- [ ] Implement Distillery and Oven. Both use glass bottles instead of clay bottles to take fumes. (Model for oven done, distillery will be done afterwards) (Oven in progress)
- [ ] Implement chalk glyphs (Enochian script, textures should be greyscaled so other colors can be applied to them, similar to candles)
- [ ] Implement trees, and their generation
- [ ] Fix any derpiness with generation
- [x] Make white sage drop from dead bushes
- [x] Meta all of the gemstones, and associated blocks, ores, and ingredients
- [x] Make salt barriers damage arthropods for now, implement more functionality in later updates
- [ ] New ingredients, ranging from fumes, to new mob drops. (Heavy WIP)
- [x] Finish up crop textures
- [ ] Some localizations?
- [ ] JEI Support? (Plugin planned)
- [ ] Wand?

**Comment by BunnyCinnamon** [comment]
What is the other stuff and things?

**Comment by Sunconure11** [comment]
Various random things that haven't simply been done yet, ranging from minor things like implementing all of the new potion items (as well as textures for all of the crops which I need to get onto at some point), to major things like massive rewrites of the code and what not, depending on what arises.

**Comment by Kadamitas** [comment]
What textures can I help make and where do I post them?

**Comment by BunnyCinnamon** [comment]
Can you join Discord? Hmmmm

**Comment by Kadamitas** [comment]
whats the link?

**Comment by BunnyCinnamon** [comment]
https://discord.gg/7epdM7

**Comment by Sunconure11** [comment]
I've expanded this issue a bit, and made it into a roadmap that simplifies the contents of the first release a bit easier.

**Comment by xenxero1** [comment]
Will this be an official release curse-forge side? Or more just a publicly accessible copy?

**Comment by Sunconure11** [comment]
Both.

**Comment by groting** [comment]
If you provide lang file, I can do Russian localization for this mod.

**Comment by Sunconure11** [comment]
https://github.com/Um-Mitternacht/Witchworks/tree/1.11.2/src/main/resources/assets/witchworks/lang

They're under here, but I'd wait a bit. More stuff is coming. A lot more stuff.

**Comment by groting** [comment]
Translate extra lines is easy. If you do not want to change the lines already written, I can start the translation.

**Comment by Sunconure11** [comment]
The gemstones are probably going to get metadata not too long from now, as are their ores and what not. You can do it if you wish, though.

Also, the oven and some fumes are being planned for fairly soon.

**Comment by the-pieman** [comment]
What would it take to give this a test-run? I'm looking over what you've got as far as code goes and I'm really interested. Long-time Witchery fan so I would like to see how it compares to its potential replacement. Was always a bit sour that Emoniph was so tight-lipped about his source code.

**Comment by groting** [comment]
Mr. the-pieman. There is little functionality for testing yet. But you can estimate the design of the mod by downloading the pre-alpha release from this page: https://github.com/Um-Mitternacht/Witchworks/releases (1.10.2).

**Comment by darthvader45** [comment]
Honestly I liked the clay bottles rather than the glass bottles, although I can understand you wanting to diverge slightly from how Emoniph made his mod.  Though I'd stick to the mythology for the most part like he did.

Suggestions:
  
1. Any chance of the vampire powers/Lilith?  Loved how you had to perform a rather simple ritual, lead a woman to the Nether to reveal herself as Lilith, and then defeat her in battle to become a vampire.  

2. The werewolf totem for the werewolf power is amazing as well.  To get powers and become the beast incarnate.

3.  Perhaps utilize pigmen-esque mechanics and when the player has performed a taboo ritual (any ritual with infernal chalk) within a certain distance of a village, witch hunters come out to defeat them?  Witch hunters would occasionally spawn in a walled village, much like the guards, in their own structure.

**Comment by Sunconure11** [comment]
All 3 are returning at some point

**Comment by darthvader45** [comment]
Sounds amazing.  Keep us posted on progress.
