### ISSUE TITLE
Obstacles to go through before moving to 1.12

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Wiccan_Arts#29]
_1.12 is far from ready in usage, and yet it should be moved to at some point, due to the massive amount of changes 1.13 will bring._

- [ ] Finding a suitable time to start the 1.12 port (I imagine sometime around August or September, depending on how long it takes to stabilize, though it could also end up happening after the first release)
- [x] MCP Mappings for 1.12
- [ ] All dependencies must have 1.12 ports (baubles is all that is left, all other dependencies moved really fast, however, this has been delayed with changes that LLibrary might have to undergo)
- [ ] Forge must stabilize a bit. (Current issues show this is not really the case, give it a few months)
- [ ] Figure out all of the new changes, such as recipe changes, and what not.
- [x] At least one recommended release of Forge for 1.12 (On 6/28/2017, there will be one, according to Lexmanos)
- [ ] The fiasco involving coremods must be fully resolved, as this mod is reliant on at least one dependency that uses a coremod.
- [ ] Upon hitting 1.12, codebase would need to be overhauled. https://twitter.com/LexManos/status/876893824970182658

**Comment by Sunconure11** [comment]
Closing as this is no longer relevant.
